angular.module('apf.util').factory('ColumnsConfig', [function columnsConfigFactory () {
  'use strict';
  return {
    rankColumnWidth: 50,
    playerColumnWidth: 125,
    positionColumnWidth: 25,
    teamColumnWidth: 25,
    bestColumnWidth: 25,
    worstColumnWidth: 25,
    averageColumnWidth: 25,
    stdDevColumnWidth: 100,
    nameColumnWidth: 160,
    cpuUsageColumnWidth: 150,
    cpuUsageTitleWidth: 95,
    memoryUsageColumnWidth: 180,
    memoryUsageTitleWidth: 135,
    networkUsageColumnWidth: 220,
    networkUsageTitleWidth: 150,
    nodesColumnWidth: 120,
    podsColumnWidth: 120,
    containersColumnWidth: 160,
    servicesColumnWidth: 125,
    registriesColumnWidth: 130,
    imagesColumnWidth: 140,
    projectsColumnWidth: 140,
    routesColumnWidth: 130,
    replicatorsColumnWidth: 150,
    uptimeColumnWidth: 150,
    providerColumnWidth: 160,
    sessionsColumnWidth: 125,
    serverGroupsColumnWidth: 175,
    clustersColumnWidth: 140,
    hostsColumnWidth: 140,
    dataStoresColumnWidth: 140,
    vmsColumnWidth: 140,
    templatesColumnWidth: 140
  };
}]);
